# Generated by Django 5.2.7 on 2025-11-01 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('descripcion', models.TextField(max_length=500)),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor')),
            ],
        ),
    ]
