# Generated by Django 5.2.7 on 2025-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_detalle_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rut_empresa', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
